const rawDoctors = [
    // Cardiologists in Hyderabad
    {
        name: "Dr. Ramesh Kumar",
        specialty: "Cardiologist",
        place: "Hyderabad",
        hospital: "Apollo Hospital",
        hospitalImage: "https://medicaldialogues.in/h-upload/2023/01/19/40x30_198899-apollo-hospital-1.webp",
        rating: 4.8,
        suggestion: "This Hospital and Doctor is best for Cardiologist in Hyderabad",
        timing: "9:00 AM - 1:00 PM",
        status: "Available",
        location: "Jubilee Hills, Rd Number 72, opposite Bharatiya Vidya Bhavan School, Film Nagar, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Suresh Reddy",
        specialty: "Cardiologist",
        place: "Hyderabad",
        hospital: "Yashoda Hospital",
        hospitalImage: "https://www.myhospitalnow.com/hospitals/storage/hospital_profile/2023-05-03-1758955903_1719917382.jpg",
        rating: 4.3,
        timing: "10:00 AM - 4:00 PM",
        status: "Available",
        location: "Survey No. 41/14, JNTU to Hitech City Main Road, Khanamet Village, Kothaguda, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Anitha Rao",
        specialty: "Cardiologist",
        place: "Hyderabad",
        hospital: "Medicover Hospital",
        hospitalImage: "https://www.medicoverhospitals.in/images/hospitals/city/hitec-city-hyderabad-800.webp",
        rating: 4.6,
        timing: "11:00 AM - 3:00 PM",
        status: "Available",
        location: "Behind Cyber Towers, In the Lane of IBIS Hotels, HUDA Techno Enclave, HITEC City, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Ravi Shankar",
        specialty: "Cardiologist",
        place: "Hyderabad",
        hospital: "KIMS Hospital",
        hospitalImage: "https://medicaldialogues.in/wp-content/uploads/2017/01/KIMS-Hospitals-Kondapur.jpg",
        rating: 4.2,
        timing: "8:00 AM - 12:00 PM",
        status: "Available",
        location: "1-112/86, Survey No 55/ EE, Kondapur Village, Serilingampally Mandal, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Anjali Mehta",
        specialty: "Cardiologist",
        place: "Hyderabad",
        hospital: "Star Hospital",
        hospitalImage: "https://hyderabadboss.com/wp-content/uploads/2016/10/star-hospitals.jpg",
        rating: 4.6,
        timing: "11:00 AM - 3:00 PM",
        status: "Available",
        location: "8-2-596/5, Road No. 10, Gaffar Khan Colony, Banjara Hills, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // Cardiologists in Secunderabad
    {
        name: "Dr. Vivek Reddy",
        specialty: "Cardiologist",
        place: "Secunderabad",
        hospital: "Yashoda Hospital",
        hospitalImage: "https://www.yashodahospitals.com/wp-content/uploads/2024/12/Secunderabad-unit.png",
        rating: 4.8,
        suggestion: "This Hospital and Doctor is best for Cardiologist in Secunderabad",
        timing: "9:00 AM - 1:00 PM",
        status: "Available",
        location: "Alexander Rd, Kummari Guda, Shivaji Nagar, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Charan",
        specialty: "Cardiologist",
        place: "Secunderabad",
        hospital: "Apollo Hospital",
        hospitalImage: "https://images1-fabric.practo.com/practices/936372/apollo-hospital-hyderabad-5cee1def74974.JPG",
        suggestion: "This Hospital and Doctor is best for Cardiologist in Secunderabad",
        rating: 4.3,
        timing: "10:00 AM - 4:00 PM",
        status: "Available",
        location: "Pollicetty Towers, St Johns Rd, beside KEYES HIGH SCHOOL FOR GIRLS, Regimental Bazaar, Shivaji Nagar, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Raghu Rama",
        specialty: "Cardiologist",
        place: "Secunderabad",
        hospital: "KIMS Hospital",
        hospitalImage: "https://www.cnexguidance.com/wp-content/uploads/2019/08/KIMS-Hospital-Secunderabad.jpg",
        rating: 4.6,
        timing: "11:00 AM - 3:00 PM",
        status: "Available",
        location: "1-8-31/1, Minister Road Krishna Nagar Colony, Ramgopalpet, Begumpet, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Gnaneshwar Rao",
        specialty: "Cardiologist",
        place: "Secunderabad",
        hospital: "Gandhi Hospital",
        hospitalImage: "https://media.telanganatoday.com/wp-content/uploads/2025/04/Gandhi-Hospital.jpg",
        rating: 4.2,
        timing: "8:00 AM - 12:00 PM",
        status: "Available",
        location: "M.I.G.H colony, Musheerabad, Walker Town, Padmarao Nagar, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Navadeep Reddy",
        specialty: "Cardiologist",
        place: "Secunderabad",
        hospital: "Medicover Hospital",
        hospitalImage: "https://skedoccoresa.blob.core.windows.net/skedoc-images/hospitalimages/de4d4f49-515f-4183-bdbc-38aa900bc163.png",
        rating: 4.6,
        timing: "11:00 AM - 3:00 PM",
        status: "Available",
        location: "Sarojini Devi Rd, Regimental Bazaar, Shivaji Nagar, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // Cardiologists in Medchal-Malkajgiri
    {
        name: "Dr. Ravi Kumar",
        specialty: "Cardiologist",
        place: "Medchal-Malkajgiri",
        hospital: "Medinova Hospital",
        hospitalImage: "https://mims.edu.in/wp-content/uploads/elementor/thumbs/Medinova-N-ra2ucx3s6bgar8qutvwgsd1cos24i0fputqueguby8.jpg",
        rating: 4.8,
        suggestion: "This Hospital and Doctor is best for Cardiologist in Medchal-Malkajgiri",
        timing: "9:00 AM - 1:00 PM",
        status: "Available",
        location: "13-254, NH 44, opp. Asian Mukund theatre, Chandra Nagar, Medchal",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Laxmikanth Reddy",
        specialty: "Cardiologist",
        place: "Medchal-Malkajgiri",
        hospital: "Malla Reddy Narayana Multispeciality Hospital",
        hospitalImage: "https://content.jdmagicbox.com/v2/comp/hyderabad/a8/040pxx40.xx40.090630094639.a4a8/catalogue/mallareddy-narayana-multispeciality-hospital-jeedimetla-hyderabad-hospitals-f7a1m6gqnl.jpg",
        rating: 4.3,
        timing: "10:00 AM - 4:00 PM",
        status: "Available",
        location: "1-1-216, Suraram'X' Roads, Jeedimetla Medchal-malkajgiri",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // Cardiologists in Rangareddy
    {
        name: "Dr. Ramu Kumar",
        specialty: "Cardiologist",
        place: "Rangareddy",
        hospital: "Trident Hospital",
        hospitalImage: "https://lh3.googleusercontent.com/gps-cs-s/AHVAweoGGfY8aFF09T9gXIMtYn7nH8kEVn-1xXMyRC1FoeNOPlc6CX-pKOlaqWwcX8dAi7Xxfz5DKiNO0YGM40zV5dycsdsBO8aX9D7i6kz6gWo5kTqlv43u9BxisG4fixi5SBTvezavaw=s1360-w1360-h1020-rw",
        rating: 4.8,
        suggestion: "This Hospital and Doctor is best for Cardiologist in Rangareddy",
        timing: "9:00 AM - 1:00 PM",
        status: "Available",
        location: " 23_178/A, Madhura Nagar, Shamshabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Tarun Reddy",
        specialty: "Cardiologist",
        place: "Rangareddy",
        hospital: "Lims Hospital",
        hospitalImage: "https://lh3.googleusercontent.com/p/AF1QipPPjAD81Yno1zyd4AltpkhK66lEQ4cp1lx9j-CW=s1360-w1360-h1020-rw",
        rating: 4.3,
        timing: "10:00 AM - 4:00 PM",
        status: "Available",
        location: "Plot No 98 Door No 23-172 Shamshabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // Cardiologist in Sangareddy
    {
        name: "Dr. Ravi Kumar",
        specialty: "Cardiologist",
        place: "Sangareddy",
        hospital: "Keerthi Hospital",
        hospitalImage: "https://lh3.googleusercontent.com/gps-cs-s/AHVAweqklDB9MEqL7adGoExFh0yrWxtKn7l-Y6vt33b-SLmlNMPTdRsV_FbDL-dbMyHrGnsDV4izVbg7GNHw7N7fcvis98M_8OAniGs25QxulfFajnJ6PsGa9wcSk7pAGoj2HWTSALNJ=s1360-w1360-h1020-rw",
        rating: 4.8,
        suggestion: "This Hospital and Doctor is best for Cardiologist in Sangareddy",
        timing: "9:00 AM - 1:00 PM",
        status: "Available",
        location: "X Roads Fasalwadi, Sangareddy",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // Dermatologists in Hyderabad
    {
        name: "Dr. Hima Sekhar",
        specialty: "Dermatologist",
        place: "Hyderabad",
        hospital: "Apollo Hospital",
        hospitalImage: "https://medicaldialogues.in/h-upload/2023/01/19/40x30_198899-apollo-hospital-1.webp",
        rating: 4.8,
        suggestion: "This Hospital and Doctor is best for Dermatologist in Hyderabad",
        timing: "9:00 AM - 1:00 PM",
        status: "Available",
        location: "Jubilee Hills, Rd Number 72, opposite Bharatiya Vidya Bhavan School, Film Nagar, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Jayaram",
        specialty: "Dermatologist",
        place: "Hyderabad",
        hospital: "Yashoda Hospital",
        hospitalImage: "https://www.myhospitalnow.com/hospitals/storage/hospital_profile/2023-05-03-1758955903_1719917382.jpg",
        rating: 4.3,
        timing: "10:00 AM - 4:00 PM",
        status: "Available",
        location: "Survey No. 41/14, JNTU to Hitech City Main Road, Khanamet Village, Kothaguda, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Srinivas",
        specialty: "Dermatologist",
        place: "Hyderabad",
        hospital: "Care Hospitals",
        hospitalImage: "https://www.carehospitals.com/assets/images/main/care-hitech-new.webp",
        rating: 4.6,
        timing: "11:00 AM - 3:00 PM",
        status: "Available",
        location: "Block A, Old Mumbai Hwy, near Cyberabad Police Commissionerate, Jayabheri Pine Valley, HITEC City, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Deepak",
        specialty: "Dermatologist",
        place: "Hyderabad",
        hospital: "KIMS Hospital",
        hospitalImage: "https://medicaldialogues.in/wp-content/uploads/2017/01/KIMS-Hospitals-Kondapur.jpg",
        rating: 4.2,
        timing: "8:00 AM - 12:00 PM",
        status: "Not Available",
        location: "1-112/86, Survey No 55/ EE, Kondapur Village, Serilingampally Mandal, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Pavan",
        specialty: "Dermatologist",
        place: "Hyderabad",
        hospital: "Medicover Hospital",
        hospitalImage: "https://www.medicoverhospitals.in/images/hospitals/city/hitec-city-hyderabad-800.webp",
        rating: 4.6,
        timing: "11:00 AM - 3:00 PM",
        status: "Available",
        location: "sarojini Devi Rd, Regimental Bazaar, Shivaji Nagar, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // Dermatologists in Secunderabad
    {
        name: "Dr. Sai kumar",
        specialty: "Dermatologist",
        place: "Secunderabad",
        hospital: "Apollo Hospital",
        hospitalImage: "https://images1-fabric.practo.com/practices/936372/apollo-hospital-hyderabad-5cee1def74974.JPG",
        rating: 4.8,
        suggestion: "This Hospital and Doctor is best for Dermatologist in Secunderabad",
        timing: "9:00 AM - 1:00 PM",
        status: "Available",
        location: "Pollicetty Towers, St Johns Rd, beside KEYES HIGH SCHOOL FOR GIRLS, Regimental Bazaar, Shivaji Nagar, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Varun",
        specialty: "Dermatologist",
        place: "Secunderabad",
        hospital: "Yashoda Hospital",
        hospitalImage: "https://www.yashodahospitals.com/wp-content/uploads/2024/12/Secunderabad-unit.png",
        rating: 4.3,
        timing: "10:00 AM - 4:00 PM",
        status: "Available",
        location: "Alexander Rd, Kummari Guda, Shivaji Nagar, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Srilakshmi",
        specialty: "Dermatologist",
        place: "Secunderabad",
        hospital: "Gandhi Hospital",
        hospitalImage: "https://media.telanganatoday.com/wp-content/uploads/2025/04/Gandhi-Hospital.jpg",
        rating: 4.6,
        timing: "11:00 AM - 3:00 PM",
        status: "Available",
        location: "M.I.G.H colony, Musheerabad, Walker Town, Padmarao Nagar, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Chandu",
        specialty: "Dermatologist",
        place: "Secunderabad",
        hospital: "KIMS Hospital",
        hospitalImage: "https://www.cnexguidance.com/wp-content/uploads/2019/08/KIMS-Hospital-Secunderabad.jpg",
        rating: 4.2,
        timing: "8:00 AM - 12:00 PM",
        status: "Available",
        location: "1-8-31/1, Minister Road Krishna Nagar Colony, Ramgopalpet, Begumpet, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Jithendra Reddy",
        specialty: "Dermatologist",
        place: "Secunderabad",
        hospital: "V care Hospital",
        hospitalImage: "https://lh3.googleusercontent.com/p/AF1QipP6PJR3ZrwPxx9XCllrVoXu5f-8bFqjC83zEHLL=s1360-w1360-h1020-rw",
        rating: 4.6,
        timing: "11:00 AM - 3:00 PM",
        status: "Available",
        location: "Aishwarya Chambers, D.No:1-19-71/A-81/2, MAIN ROAD, Lakshmipuram Colony, Rukminipuri Colony, A. S. Rao Nagar, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // Dermatologist in Patancheruvu
    {
        name: "Dr. Dinesh Kumar",
        specialty: "Dermatologist",
        place: "Patancheruvu",
        hospital: "Amedha Hospital",
        hospitalImage: "https://skedoccoresa.blob.core.windows.net/skedoc-images/hospitalimages/4c35669c-cb3a-4f5a-85e7-d3f070b04c09.jpeg",
        rating: 4.8,
        suggestion: "This Hospital and Doctor is best for Dermatologist in Patancheruvu",
        timing: "9:00 AM - 1:00 PM",
        status: "Available",
        location: "H, No-14-25, beside union Bank, Sreeram Nagar Colony, Patancheruvu",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // Dermatologist in Rangareddy
    {
        name: "Dr. Anikith Kumar",
        specialty: "Dermatologist",
        place: "Rangareddy",
        hospital: "Trident Hospital",
        hospitalImage: "https://lh3.googleusercontent.com/gps-cs-s/AHVAweoGGfY8aFF09T9gXIMtYn7nH8kEVn-1xXMyRC1FoeNOPlc6CX-pKOlaqWwcX8dAi7Xxfz5DKiNO0YGM40zV5dycsdsBO8aX9D7i6kz6gWo5kTqlv43u9BxisG4fixi5SBTvezavaw=s1360-w1360-h1020-rw",
        rating: 4.8,
        suggestion: "This Hospital and Doctor is best for Dermatologist in Rangareddy",
        timing: "9:00 AM - 1:00 PM",
        status: "Available",
        location: " 23_178/A, Madhura Nagar, Shamshabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // Dermatologists in Siddipet
    {
        name: "Dr. Ravi Kumar",
        specialty: "Dermatologist",
        place: "Siddipet",
        hospital: "Lalitha Bhavani Hospital",
        hospitalImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTw_pP6tThAqOJMnaGz833k7RYquJR4s8ewKA&s",
        rating: 4.8,
        suggestion: "This Hospital and Doctor is best for Dermatologist in Siddipet",
        timing: "9:00 AM - 1:00 PM",
        status: "Available",
        location: "Beside Seetharamanjaneya, Theatre Street Shivaji Nagar",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Laxmikanth Reddy",
        specialty: "Dermatologist",
        place: "Siddipet",
        hospital: "Adhya Skin and Hair Transplant Clinic",
        hospitalImage: "https://content3.jdmagicbox.com/v2/comp/siddipet/d3/9999p8457.8457.230818165420.c2d3/catalogue/adhya-skin-and-hair-transplant-hospital-bharath-nagar-siddipet-dermatology-hospitals-yqjpnmbyu7.jpg",
        rating: 4.3,
        timing: "10:00 AM - 4:00 PM",
        status: "Available",
        location: "ADHYA HOSPITAL BULIDING, opposite Bazar cellar, Bharath Nagar, Bharth Nagar, Siddipet",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // Gastroenterologists in Hyderabad
    {
        name: "Dr. Gopal Reddy",
        specialty: "Gastroenterologist",
        place: "Hyderabad",
        hospital: "AIG Hospital",
        hospitalImage: "https://static.toiimg.com/thumb/resizemode-4,width-1280,height-720,msid-78945397/78945397.jpg",
        rating: 4.8,
        suggestion: "This Hospital and Doctor is best for Gastroenterologist in Hyderabad",
        timing: "9:00 AM - 1:00 PM",
        status: "Available",
        location: "1-66/AIG/2 to 5, Mindspace Rd, P Janardhan Reddy Nagar, Gachibowli, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Mahesh Kumar",
        specialty: "Gastroenterologist",
        place: "Hyderabad",
        hospital: "PACE Hospital",
        hospitalImage: "https://irp.cdn-website.com/69c0b277/dms3rep/multi/PACE+Hospitals+-+HITEC+City.jpg",
        rating: 4.3,
        timing: "10:00 AM - 4:00 PM",
        status: "Available",
        location: "Metro Pillar Number C1775, 18, Hitech City Rd, HUDA Techno Enclave, HITEC City, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Anil Kumar",
        specialty: "Gastroenterologist",
        place: "Hyderabad",
        hospital: "NIMS Hospital",
        hospitalImage: "https://th-i.thgim.com/public/migration_catalog/article13462295.ece/alternates/FREE_1200/HY22NIMS",
        rating: 4.6,
        timing: "11:00 AM - 3:00 PM",
        status: "Available",
        location: "Punjagutta Rd, Punjagutta Market, Punjagutta, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Praveen",
        specialty: "Gastroenterologist",
        place: "Hyderabad",
        hospital: "Yashoda Hospital",
        hospitalImage: "https://www.myhospitalnow.com/hospitals/storage/hospital_profile/2023-05-03-1758955903_1719917382.jpg",
        rating: 4.2,
        timing: "8:00 AM - 12:00 PM",
        status: "Available",
        location: "Survey No. 41/14, JNTU to Hitech City Main Road, Khanamet Village, Kothaguda, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Ritesh",
        specialty: "Gastroenterologist",
        place: "Hyderabad",
        hospital: "Apollo Hospital",
        hospitalImage: "https://medicaldialogues.in/h-upload/2023/01/19/40x30_198899-apollo-hospital-1.webp",
        rating: 4.6,
        timing: "11:00 AM - 3:00 PM",
        status: "Available",
        location: "Jubilee Hills, Rd Number 72, opposite Bharatiya Vidya Bhavan School, Film Nagar, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // Gastroenterologists in Secunderabad
    {
        name: "Dr. Arun",
        specialty: "Gastroenterologist",
        place: "Secunderabad",
        hospital: "Apollo Hospital",
        hospitalImage: "https://images1-fabric.practo.com/practices/936372/apollo-hospital-hyderabad-5cee1def74974.JPG",
        rating: 4.8,
        suggestion: "This Hospital and Doctor is best for Gastroenterologist in Secunderabad",
        timing: "9:00 AM - 1:00 PM",
        status: "Available",
        location: "Pollicetty Towers, St Johns Rd, beside KEYES HIGH SCHOOL FOR GIRLS, Regimental Bazaar, Shivaji Nagar, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Srikanth kumar",
        specialty: "Gastroenterologist",
        place: "Secunderabad",
        hospital: "Yashoda Hospital",
        hospitalImage: "https://www.yashodahospitals.com/wp-content/uploads/2024/12/Secunderabad-unit.png",
        rating: 4.3,
        timing: "10:00 AM - 4:00 PM",
        status: "Available",
        location: "Alexander Rd, Kummari Guda, Shivaji Nagar, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Raghu",
        specialty: "Gastroenterologist",
        place: "Secunderabad",
        hospital: "Gandhi Hospital",
        hospitalImage: "https://media.telanganatoday.com/wp-content/uploads/2025/04/Gandhi-Hospital.jpg",
        rating: 4.6,
        timing: "11:00 AM - 3:00 PM",
        status: "Available",
        location: "M.I.G.H colony, Musheerabad, Walker Town, Padmarao Nagar, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Gnanesh",
        specialty: "Gastroenterologist",
        place: "Secunderabad",
        hospital: "KIMS Hospital",
        hospitalImage: "https://www.cnexguidance.com/wp-content/uploads/2019/08/KIMS-Hospital-Secunderabad.jpg",
        rating: 4.2,
        timing: "8:00 AM - 12:00 PM",
        status: "Available",
        location: "1-8-31/1, Minister Road Krishna Nagar Colony, Ramgopalpet, Begumpet, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Sanjay Reddy",
        specialty: "Gastroenterologist",
        place: "Secunderabad",
        hospital: "Medicover Hospital",
        hospitalImage: "https://skedoccoresa.blob.core.windows.net/skedoc-images/hospitalimages/de4d4f49-515f-4183-bdbc-38aa900bc163.png",
        rating: 4.6,
        timing: "11:00 AM - 3:00 PM",
        status: "Available",
        location: "sarojini Devi Rd, Regimental Bazaar, Shivaji Nagar, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // Gastroenterologists in Medchal-Malkajgiri
    {
        name: "Dr. Santhosh Kumar",
        specialty: "Gastroenterologist",
        place: "Medchal-Malkajgiri",
        hospital: "Medinova Hospital",
        hospitalImage: "https://mims.edu.in/wp-content/uploads/elementor/thumbs/Medinova-N-ra2ucx3s6bgar8qutvwgsd1cos24i0fputqueguby8.jpg",
        rating: 4.8,
        suggestion: "This Hospital and Doctor is best for Gastroenterologist in Medchal",
        timing: "9:00 AM - 1:00 PM",
        status: "Available",
        location: "13-254, NH 44, opp. Asian Mukund theatre, Chandra Nagar, Medchal",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Ravikanth Reddy",
        specialty: "Gastroenterologist",
        place: "Medchal-Malkajgiri",
        hospital: "Malla Reddy Narayana Multispeciality Hospital",
        hospitalImage: "https://content.jdmagicbox.com/v2/comp/hyderabad/a8/040pxx40.xx40.090630094639.a4a8/catalogue/mallareddy-narayana-multispeciality-hospital-jeedimetla-hyderabad-hospitals-f7a1m6gqnl.jpg",
        rating: 4.3,
        timing: "10:00 AM - 4:00 PM",
        status: "Available",
        location: "1-1-216, Suraram'X' Roads, Jeedimetla Medchal-malkajgiri",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Sandeep Rao",
        specialty: "Gastroenterologist",
        place: "Medchal-Malkajgiri",
        hospital: "Renova Hospital",
        hospitalImage: "https://medifyhome.com/wp-content/uploads/2023/12/Untitled-design-4.png",
        rating: 4.6,
        timing: "11:00 AM - 3:00 PM",
        status: "Available",
        location: "Gachibowli, Medchal Rd, NCL Enclave South, Petbasheerabad, Kompally",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Rohit",
        specialty: "Gastroenterologist",
        place: "Medchal-Malkajgiri",
        hospital: "MedOne Hospital",
        hospitalImage: "https://skedoccoresa.blob.core.windows.net/skedoc-images/hospitalimages/6becc540-ab91-4f4f-9554-befdc1f825f5.jpeg",
        rating: 4.2,
        timing: "8:00 AM - 12:00 PM",
        status: "Available",
        location: "Survey No.42, Pipeline Rd, next to Centro, Suchitra, Kompally",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // Gastroenterologist in Rangareddy
    {
        name: "Dr. Mohit Kumar",
        specialty: "Gastroenterologist",
        place: "Rangareddy",
        hospital: "Lims hospital",
        hospitalImage: "https://lh3.googleusercontent.com/p/AF1QipPPjAD81Yno1zyd4AltpkhK66lEQ4cp1lx9j-CW=s1360-w1360-h1020-rw",
        rating: 4.8,
        suggestion: "This Hospital and Doctor is best for Gastroenterologist in Rangareddy",
        timing: "9:00 AM - 1:00 PM",
        status: "Available",
        location: "Plot No 98 Door No 23-172 Shamshabad, Rangareddy",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // Neurologists in Hyderabad
    {
        name: "Dr. Naresh",
        specialty: "Neurologist",
        place: "Hyderabad",
        hospital: "Apollo Hospital",
        hospitalImage: "https://medicaldialogues.in/h-upload/2023/01/19/40x30_198899-apollo-hospital-1.webp",
        rating: 4.8,
        suggestion: "This Hospital and Doctor is best for Neurologist in Hyderabad",
        timing: "9:00 AM - 1:00 PM",
        status: "Available",
        location: "Jubilee Hills, Rd Number 72, opposite Bharatiya Vidya Bhavan School, Film Nagar, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Prakash",
        specialty: "Neurologist",
        place: "Hyderabad",
        hospital: "Yashoda Hospital",
        hospitalImage: "https://www.myhospitalnow.com/hospitals/storage/hospital_profile/2023-05-03-1758955903_1719917382.jpg",
        rating: 4.3,
        timing: "10:00 AM - 4:00 PM",
        status: "Available",
        location: "Survey No. 41/14, JNTU to Hitech City Main Road, Khanamet Village, Kothaguda, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Devendra Rao",
        specialty: "Neurologist",
        place: "Hyderabad",
        hospital: "Care Hospitals",
        hospitalImage: "https://www.carehospitals.com/assets/images/main/care-hitech-new.webp",
        rating: 4.6,
        timing: "11:00 AM - 3:00 PM",
        status: "Available",
        location: "Block A, Old Mumbai Hwy, near Cyberabad Police Commissionerate, Jayabheri Pine Valley, HITEC City, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Shanakar",
        specialty: "Neurologist",
        place: "Hyderabad",
        hospital: "KIMS Hospital",
        hospitalImage: "https://medicaldialogues.in/wp-content/uploads/2017/01/KIMS-Hospitals-Kondapur.jpg",
        rating: 4.2,
        timing: "8:00 AM - 12:00 PM",
        status: "Not Available",
        location: "1-112/86, Survey No 55/ EE, Kondapur Village, Serilingampally Mandal, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Manoj",
        specialty: "Neurologist",
        place: "Hyderabad",
        hospital: "NIMS Hospital",
        hospitalImage: "https://th-i.thgim.com/public/migration_catalog/article13462295.ece/alternates/FREE_1200/HY22NIMS",
        rating: 4.6,
        timing: "11:00 AM - 3:00 PM",
        status: "Available",
        location: "Punjagutta Rd, Punjagutta Market, Punjagutta, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // Neurologists in Secunderabad
    {
        name: "Dr. Vinay",
        specialty: "Neurologist",
        place: "Secunderabad",
        hospital: "Apollo Hospital",
        hospitalImage: "https://images1-fabric.practo.com/practices/936372/apollo-hospital-hyderabad-5cee1def74974.JPG",
        rating: 4.8,
        suggestion: "This Hospital and Doctor is best for Neurologist in Secunderabad",
        timing: "9:00 AM - 1:00 PM",
        status: "Available",
        location: "Pollicetty Towers, St Johns Rd, beside KEYES HIGH SCHOOL FOR GIRLS, Regimental Bazaar, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Bhaskar",
        specialty: "Neurologist",
        place: "Secunderabad",
        hospital: "Yashoda Hospital",
        hospitalImage: "https://www.yashodahospitals.com/wp-content/uploads/2024/12/Secunderabad-unit.png",
        rating: 4.3,
        timing: "10:00 AM - 4:00 PM",
        status: "Available",
        location: "Alexander Rd, Kummari Guda, Shivaji Nagar, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Venkatesh",
        specialty: "Neurologist",
        place: "Secunderabad",
        hospital: "Gandhi Hospital",
        hospitalImage: "https://media.telanganatoday.com/wp-content/uploads/2025/04/Gandhi-Hospital.jpg",
        rating: 4.6,
        timing: "11:00 AM - 3:00 PM",
        status: "Available",
        location: "M.I.G.H colony, Musheerabad, Walker Town, Padmarao Nagar, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Srinivas",
        specialty: "Neurologist",
        place: "Secunderabad",
        hospital: "KIMS Hospital",
        hospitalImage: "https://www.cnexguidance.com/wp-content/uploads/2019/08/KIMS-Hospital-Secunderabad.jpg",
        rating: 4.2,
        timing: "8:00 AM - 12:00 PM",
        status: "Available",
        location: "1-8-31/1, Minister Road Krishna Nagar Colony, Ramgopalpet, Begumpet, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Shekhar",
        specialty: "Neurologist",
        place: "Secunderabad",
        hospital: "Medicover Hospital",
        hospitalImage: "https://www.medicoverhospitals.in/images/hospitals/city/hitec-city-hyderabad-800.webp",
        rating: 4.6,
        timing: "11:00 AM - 3:00 PM",
        status: "Available",
        location: "Sarojini Devi Rd, Regimental Bazaar, Shivaji Nagar, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // Neurologists in Medchal-Malkajgiri
    {
        name: "Dr. Uday Kumar",
        specialty: "Neurologist",
        place: "Medchal-Malkajgiri",
        hospital: "Medinova Hospital",
        hospitalImage: "https://mims.edu.in/wp-content/uploads/elementor/thumbs/Medinova-N-ra2ucx3s6bgar8qutvwgsd1cos24i0fputqueguby8.jpg",
        rating: 4.8,
        suggestion: "This Hospital and Doctor is best for Neurologist in Medchal",
        timing: "9:00 AM - 1:00 PM",
        status: "Available",
        location: "13-254, NH 44, opp. Asian Mukund theatre, Chandra Nagar, Medchal",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Harish",
        specialty: "Neurologist",
        place: "Medchal-Malkajgiri",
        hospital: "Malla Reddy Narayana Multispeciality Hospital",
        hospitalImage: "https://content.jdmagicbox.com/v2/comp/hyderabad/a8/040pxx40.xx40.090630094639.a4a8/catalogue/mallareddy-narayana-multispeciality-hospital-jeedimetla-hyderabad-hospitals-f7a1m6gqnl.jpg",
        rating: 4.3,
        timing: "10:00 AM - 4:00 PM",
        status: "Available",
        location: "1-1-216, Suraram'X' Roads, Jeedimetla Medchal-malkajgiri",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Chandrakanth",
        specialty: "Neurologist",
        place: "Medchal-Malkajgiri",
        hospital: "Renova Hospital",
        hospitalImage: "https://medifyhome.com/wp-content/uploads/2023/12/Untitled-design-4.png",
        rating: 4.6,
        timing: "11:00 AM - 3:00 PM",
        status: "Available",
        location: "34 34/A Medchal Rd, Gachibowli, Medchal Rd, NCL Enclave South, Petbasheerabad, Kompally",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Tarun",
        specialty: "Neurologist",
        place: "Medchal-Malkajgiri",
        hospital: "MedOne Hospital",
        hospitalImage: "https://skedoccoresa.blob.core.windows.net/skedoc-images/hospitalimages/6becc540-ab91-4f4f-9554-befdc1f825f5.jpeg",
        rating: 4.2,
        timing: "8:00 AM - 12:00 PM",
        status: "Available",
        location: "Survey No.42, Pipeline Rd, next to Centro, Suchitra, Kompally",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Laxman",
        specialty: "Neurologist",
        place: "Medchal-Malkajgiri",
        hospital: "Goutham Hospital",
        hospitalImage: "https://content3.jdmagicbox.com/v2/comp/hyderabad/w6/040pxx40.xx40.190506191937.z8w6/catalogue/goutam-neuro-care-kphb-colony-hyderabad-neurologists-1sba96hz29.jpg",
        rating: 4.6,
        timing: "11:00 AM - 3:00 PM",
        status: "Available",
        location: "H.No.261, MIG, Road No. 4, Kukatpally Housing Board Colony, K P H B Phase 1, Kukatpally",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // Orthopedic Surgeons in Hyderabad
    {
        name: "Dr. Naresh",
        specialty: "orthopedic Surgeon",
        place: "Hyderabad",
        hospital: "Apollo Hospital",
        hospitalImage: "https://medicaldialogues.in/h-upload/2023/01/19/40x30_198899-apollo-hospital-1.webp",
        rating: 4.8,
        timing: "9:00 AM - 1:00 PM",
        status: "Available",
        location: "Jubilee Hills, Rd Number 72, opposite Bharatiya Vidya Bhavan School, Film Nagar, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Prakash",
        specialty: "orthopedic Surgeon",
        place: "Hyderabad",
        hospital: "Yashoda Hospital",
        hospitalImage: "https://www.myhospitalnow.com/hospitals/storage/hospital_profile/2023-05-03-1758955903_1719917382.jpg",
        rating: 4.3,
        timing: "10:00 AM - 4:00 PM",
        status: "Available",
        location: "Survey No. 41/14, JNTU to Hitech City Main Road, Khanamet Village, Kothaguda, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // Orthopedic Surgeons in Secunderabad
    {
        name: "Dr. Vinay",
        specialty: "orthopedic Surgeon",
        place: "Secunderabad",
        hospital: "Apollo Hospital",
        hospitalImage: "https://images1-fabric.practo.com/practices/936372/apollo-hospital-hyderabad-5cee1def74974.JPG",
        rating: 4.8,
        timing: "9:00 AM - 1:00 PM",
        status: "Available",
        location: "Pollicetty Towers, St Johns Rd, beside KEYES HIGH SCHOOL FOR GIRLS, Regimental Bazaar, Shivaji Nagar, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // Orthopedic Surgeons in Medchal-Malkajgiri
    {
        name: "Dr. Chandrakanth",
        specialty: "orthopedic Surgeon",
        place: "Medchal-Malkajgiri",
        hospital: "Renova Hospital",
        hospitalImage: "https://medifyhome.com/wp-content/uploads/2023/12/Untitled-design-4.png",
        rating: 4.6,
        timing: "11:00 AM - 3:00 PM",
        status: "Available",
        location: "34 34/A Medchal Rd, Gachibowli, Medchal Rd, NCL Enclave South, Petbasheerabad, Kompally",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // General Surgeons in Secunderabad
    {
        name: "Dr. Vinay",
        specialty: "General Surgeon",
        place: "Secunderabad",
        hospital: "Apollo Hospital",
        hospitalImage: "https://images1-fabric.practo.com/practices/936372/apollo-hospital-hyderabad-5cee1def74974.JPG",
        rating: 4.8,
        timing: "9:00 AM - 1:00 PM",
        status: "Available",
        location: "Pollicetty Towers, St Johns Rd, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // General Surgeons in Medchal-Malkajgiri
    {
        name: "Dr. Harish",
        specialty: "General Surgeon",
        place: "Medchal-Malkajgiri",
        hospital: "Malla Reddy Hospital",
        hospitalImage: "https://content.jdmagicbox.com/v2/comp/hyderabad/a8/040pxx40.xx40.090630094639.a4a8/catalogue/mallareddy-narayana-multispeciality-hospital-jeedimetla-hyderabad-hospitals-f7a1m6gqnl.jpg",
        rating: 4.3,
        timing: "10:00 AM - 4:00 PM",
        status: "Available",
        location: "Suraram 'X' Roads, Jeedimetla, Medchal",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // General Surgeon in Sangareddy
    {
        name: "Dr. Sreeharsha Reddy",
        specialty: "General Surgeon",
        place: "Sangareddy",
        hospital: "Sreshta Hospital",
        hospitalImage: "https://skedoccoresa.blob.core.windows.net/skedoc-images/hospitalimages/8c2ec5cc-897b-46af-989c-4380547a89a0.jpeg",
        rating: 4.8,
        suggestion: "This Hospital and Doctor is best for General Surgeon in Sangareddy",
        timing: "9:00 AM - 1:00 PM",
        status: "Available",
        location: "Number 23-72, Ashok Nagar, RC Puram, Landmark: Near Jyothi Theatre",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // General Surgeon in Karimnagar
    {
        name: "Dr. Roshan Reddy",
        specialty: "General Surgeon",
        place: "Kariminagar",
        hospital: "Medicover Hospital",
        hospitalImage: "https://lh3.googleusercontent.com/gps-cs-s/AHVAwerDtwMyHDHF_kSOgLkBGZaq8Dh50doUCEUuDLOHsyVFXh2lck21RRdq_JGp46gxhs7u-GzvjAbMqfvnaR9b5ejDCE1sLOyLF30PtCu_hPaxywHcxQ5-9qUnbo7M_EUuKiQjzPhi=s1360-w1360-h1020-rw",
        rating: 4.3,
        timing: "10:00 AM - 4:00 PM",
        status: "Available",
        location: "Old Employment Office Road Civil Hospital Back-side, Christian Colony, Karimnagar",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // Gynecologists in Hyderabad
    {
        name: "Dr. Kamala Devi",
        specialty: "gynecologist",
        place: "Hyderabad",
        hospital: "Rainbow Children's Hospital",
        hospitalImage: "https://mims.edu.in/wp-content/uploads/elementor/thumbs/Medinova-N-ra2ucx3s6bgar8qutvwgsd1cos24i0fputqueguby8.jpg",
        rating: 4.9,
        timing: "9:00 AM - 2:00 PM",
        status: "Available",
        location: "Kondapur Main Road, HUDA Techno Enclave, Gachibowli, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    {
        name: "Dr. Sangeetha Rao",
        specialty: "gynecologist",
        place: "Secunderabad",
        hospital: "Fernandez Hospital",
        hospitalImage: "https://images1-fabric.practo.com/practices/936372/apollo-hospital-hyderabad-5cee1def74974.JPG",
        rating: 4.8,
        timing: "10:00 AM - 3:00 PM",
        status: "Available",
        location: "St. Johns Road, Regimental Bazaar, Secunderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // Nephrologists in Hyderabad
    {
        name: "Dr. Prasad Rao",
        specialty: "Nephrologist",
        place: "Hyderabad",
        hospital: "NIMS Hospital",
        hospitalImage: "https://th-i.thgim.com/public/migration_catalog/article13462295.ece/alternates/FREE_1200/HY22NIMS",
        rating: 4.7,
        timing: "9:00 AM - 1:00 PM",
        status: "Available",
        location: "Punjagutta Main Rd, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // Endocrinologists
    {
        name: "Dr. Shyam Prasad",
        specialty: "Endocrinologist",
        place: "Hyderabad",
        hospital: "Apollo Hospital",
        hospitalImage: "https://medicaldialogues.in/h-upload/2023/01/19/40x30_198899-apollo-hospital-1.webp",
        rating: 4.8,
        timing: "11:00 AM - 3:00 PM",
        status: "Available",
        location: "Road No 72, Jubilee Hills, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    },
    // Otolaryngologists
    {
        name: "Dr. Suresh Kumar ENT",
        specialty: "Otolaryngologist",
        place: "Hyderabad",
        hospital: "ENT Speciality Center",
        hospitalImage: "https://www.carehospitals.com/assets/images/main/care-hitech-new.webp",
        rating: 4.7,
        timing: "10:00 AM - 1:00 PM",
        status: "Available",
        location: "Banjara Hills Road No. 1, Hyderabad",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu83J9kqtU2g72BIhD68RHSeSP77OycSCb0OWdehR5gw&s"
    }
];

const specialtyFees = {
    "Cardiologist": 800,
    "Dermatologist": 500,
    "Gastroenterologist": 600,
    "Neurologist": 1000,
    "orthopedic Surgeon": 700,
    "gynecologist": 650,
    "Nephrologist": 900,
    "Endocrinologist": 850,
    "Otolaryngologist": 550,
    "General Surgeon": 600
};

export const hardcodedDoctors = rawDoctors.map(doc => ({
    ...doc,
    consultationFee: specialtyFees[doc.specialty] || 500
}));

